---
# tasks file for testlink

- name: Enter the setup testlink stage
  import_tasks: setup_testlink.yml

- name: Enter the setting php-fpm stage
  import_tasks: setting_php-fpm.yml

- name: Enter the setting nginx stage
  import_tasks: setting_nginx.yml

- name: Enter the setting testlink stage
  import_tasks: setting_testlink.yml

- name: "=> Trigger handlers"
  meta: flush_handlers
  tags: setup

- name: Enter the check stage
  import_tasks: check.yml

# vim: ft=yaml.ansible :
