---
# tasks file for testlink

- debug: msg="==> setting for TestLink"

- name: setting testlink database connect configure
  become: true
  template:
    src: ../templates/config_db.inc.php.j2
    dest: "{{ nginx_testlink_path }}/config_db.inc.php"

# vim: ft=yaml.ansible :
